INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEHRU PLACE TERMINAL","PARAS CINEMA",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PARAS CINEMA","KALKAJI TEMPLE",0.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("KALKAJI TEMPLE","GOVIND PURI",0.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("GOVIND PURI","KALKAJI DEPOT",0.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("KALKAJI DEPOT","C-LAL CHOWK",0.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("C-LAL CHOWK","OKHLA INDUSTRIES AREA",0.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("OKHLA INDUSTRIES AREA","CROWN PLAZA",0.5);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("CROWN PLAZA","SARITA VIHAR X-LNG",2.25);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SARITA VIHAR X-LNG","JASOLA VIHAR",0.55);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("JASOLA VIHAR","SHAHEEN BAGH",0.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SHAHEEN BAGH","KALINDI KUNJ",0.45);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("KALINDI KUNJ","SECTOR-94",2.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SECTOR-94","SECTOR-18-37",2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SECTOR-18-37","NOIDA SECTOR-43",3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NOIDA SECTOR-43","BAROLA MARKET",2.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("BAROLA MARKET","SECTOR-106",3.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SECTOR-106","HOUSARY COMPLEX PHASE-2",5.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("HOUSARY COMPLEX PHASE-2","NOIDA PHASE-2",0.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEHRU PLACE TERMINAL","PARAS CINEMA",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PARAS CINEMA","N.S.I.C",0.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("N.S.I.C","MODI MILLS X-ING",0.45);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MODI MILLS X-ING","KALKA MOR",1.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("KALKA MOR","ISHWAR NAGAR",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ISHWAR NAGAR","NEW FRIENDS COLONY",0.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEW FRIENDS COLONY","ASHRAM",1.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ASHRAM","MAHARANI BAGH",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MAHARANI BAGH","GURUDWARA BALA SAHIB",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("GURUDWARA BALA SAHIB","SARAI KALE KHAN",0.95);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SARAI KALE KHAN","EAST ROAD BRIDGE",1.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("EAST ROAD BRIDGE","PWD OFFICE",1.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PWD OFFICE","NOIDA X-ING",2.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NOIDA X-ING","SAMASPUR JAGIR VILLAGE",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SAMASPUR JAGIR VILLAGE","PATPARGANJ X-ING",0.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PATPARGANJ X-ING","PANDAV NAGAR POLICE STATION",0.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PANDAV NAGAR POLICE STATION","SASHI GARDEN X-ING",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SASHI GARDEN X-ING","MAYUR VIHAR PHASE-1 POCKET-5",0.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MAYUR VIHAR PHASE-1 POCKET-5","ITI KHICRIPUR",0.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ITI KHICRIPUR","TRILOKPURI 13 BLOCK",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("TRILOKPURI 13 BLOCK","CHAND CINEMA",0.24);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("CHAND CINEMA","SUPER BAZAR",0.5);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SUPER BAZAR","KALYANPURI",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEHRU PLACE TERMINAL","SANT NAGAR",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SANT NAGAR","MOOL CHAND KHARATI RAM HOSPITAL",2.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MOOL CHAND KHARATI RAM HOSPITAL","PANT NAGAR",2.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PANT NAGAR","SUNDER NAGAR",2.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SUNDER NAGAR","PRAGATI MAIDAN",2.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PRAGATI MAIDAN","I.T.O(RING ROAD)",2.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("I.T.O(RING ROAD)","RAINY WELL",1.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("RAINY WELL","SHAKAR PUR",1.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SHAKAR PUR","JAGAT PURI A-BLOCK",3.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("JAGAT PURI A-BLOCK","SWARN CINEMA",1.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SWARN CINEMA","SEELAM PUR",2.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SEELAM PUR","BABARPUR",2.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("BABARPUR","JYOTI COLONY",0.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("JYOTI COLONY","NAND NAGAR TERMINAL",2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEHRU PLACE TERMINAL","SANT NAGAR",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SANT NAGAR","L.S.R COLLEGE",1.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("L.S.R COLLEGE","ANDREWS GANJ",1.5);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ANDREWS GANJ","PT COLLEGE KOTLA",0.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PT COLLEGE KOTLA","SUKHDEV MARKET KOTLA",0.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SUKHDEV MARKET KOTLA","JAWAHAR LAL NEHRU STADIUM",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("JAWAHAR LAL NEHRU STADIUM","KHAN MARKET",2.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("KHAN MARKET","BARODA HOUSE",2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("BARODA HOUSE","PATIALA HOUSE",0.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PATIALA HOUSE","SUPREME COURT",0.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SUPREME COURT","ITO AGCR",1.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ITO AGCR","RAINY WELL",1.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("RAINY WELL","LAXMI NAGAR",2.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("LAXMI NAGAR","NIRMAN VIHAR",2.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NIRMAN VIHAR","NEW RAJDHANI ENCLAVE",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEW RAJDHANI ENCLAVE","DDA FLATS KARKADOMA",2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("DDA FLATS KARKADOMA","YAMUNA SPORTS COMPLEX",2.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("YAMUNA SPORTS COMPLEX","RAMAPRASTH XING",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("RAMAPRASTH XING","SHAHDARA BORDER",3.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SHAHDARA BORDER","DILSHAD GARDEN POCKET P",1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NEHRU PLACE TERMINAL","PARAS CINEMA",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PARAS CINEMA","MODI MILL",1.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MODI MILL","GARHI VILLAGE",1.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("GARHI VILLAGE","P.G.D.A.V COLLEGE",0.8);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("P.G.D.A.V COLLEGE","MAHARANI BAGH",2.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MAHARANI BAGH","GURUDWARA SRI BANGLA SAHIB",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("GURUDWARA SRI BANGLA SAHIB","PWD OFFICE",3.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("PWD OFFICE","MAYUR VIHAR PHASE-1",3.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MAYUR VIHAR PHASE-1","MAYUR KUNJ",2.7);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("MAYUR KUNJ","SECTOR 15",1.2);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SECTOR 15","RAJNI GANDHA CHOWL",0.6);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("RAJNI GANDHA CHOWL","BSNL SECTOR-19",1.3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("BSNL SECTOR-19","NOIDA STADIUM",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NOIDA STADIUM","NOIDA SECTOR 12-22",1.5);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("NOIDA SECTOR 12-22","ROYAL TOWERS",3);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("ROYAL TOWERS","SABJI MANDI BUS STOP",0.9);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("SABJI MANDI BUS STOP","RO APARTMENTS",1.1);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("RO APARTMENTS","FORTIS HOSPITAL",0.4);
INSERT INTO graphs_edges(Vertex1,Vertex2,Weight) VALUES ("FORTIS HOSPITAL","SECTOR-62",1);