INSERT INTO graphs_vertices(name) VALUES ("NEHRU PLACE TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("PARAS CINEMA");
INSERT INTO graphs_vertices(name) VALUES ("KALKAJI TEMPLE");
INSERT INTO graphs_vertices(name) VALUES ("GOVIND PURI");
INSERT INTO graphs_vertices(name) VALUES ("KALKAJI DEPOT");
INSERT INTO graphs_vertices(name) VALUES ("C-LAL CHOWK");
INSERT INTO graphs_vertices(name) VALUES ("OKHLA INDUSTRIES AREA");
INSERT INTO graphs_vertices(name) VALUES ("CROWN PLAZA");
INSERT INTO graphs_vertices(name) VALUES ("SARITA VIHAR X-LNG");
INSERT INTO graphs_vertices(name) VALUES ("JASOLA VIHAR");
INSERT INTO graphs_vertices(name) VALUES ("SHAHEEN BAGH");
INSERT INTO graphs_vertices(name) VALUES ("KALINDI KUNJ");
INSERT INTO graphs_vertices(name) VALUES ("SECTOR-94");
INSERT INTO graphs_vertices(name) VALUES ("SECTOR-18-37");
INSERT INTO graphs_vertices(name) VALUES ("NOIDA SECTOR-43");
INSERT INTO graphs_vertices(name) VALUES ("BAROLA MARKET");
INSERT INTO graphs_vertices(name) VALUES ("SECTOR-106");
INSERT INTO graphs_vertices(name) VALUES ("HOUSARY COMPLEX PHASE-2");
INSERT INTO graphs_vertices(name) VALUES ("NOIDA PHASE-2");
INSERT INTO graphs_vertices(name) VALUES ("NEHRU PLACE TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("PARAS CINEMA");
INSERT INTO graphs_vertices(name) VALUES ("N.S.I.C");
INSERT INTO graphs_vertices(name) VALUES ("MODI MILLS X-ING");
INSERT INTO graphs_vertices(name) VALUES ("KALKA MOR");
INSERT INTO graphs_vertices(name) VALUES ("ISHWAR NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("NEW FRIENDS COLONY");
INSERT INTO graphs_vertices(name) VALUES ("ASHRAM");
INSERT INTO graphs_vertices(name) VALUES ("MAHARANI BAGH");
INSERT INTO graphs_vertices(name) VALUES ("GURUDWARA BALA SAHIB");
INSERT INTO graphs_vertices(name) VALUES ("SARAI KALE KHAN");
INSERT INTO graphs_vertices(name) VALUES ("EAST ROAD BRIDGE");
INSERT INTO graphs_vertices(name) VALUES ("PWD OFFICE");
INSERT INTO graphs_vertices(name) VALUES ("NOIDA X-ING");
INSERT INTO graphs_vertices(name) VALUES ("SAMASPUR JAGIR VILLAGE");
INSERT INTO graphs_vertices(name) VALUES ("PATPARGANJ X-ING");
INSERT INTO graphs_vertices(name) VALUES ("PANDAV NAGAR POLICE STATION");
INSERT INTO graphs_vertices(name) VALUES ("SASHI GARDEN X-ING");
INSERT INTO graphs_vertices(name) VALUES ("MAYUR VIHAR PHASE-1 POCKET-5");
INSERT INTO graphs_vertices(name) VALUES ("ITI KHICRIPUR");
INSERT INTO graphs_vertices(name) VALUES ("TRILOKPURI 13 BLOCK");
INSERT INTO graphs_vertices(name) VALUES ("CHAND CINEMA");
INSERT INTO graphs_vertices(name) VALUES ("SUPER BAZAR");
INSERT INTO graphs_vertices(name) VALUES ("KALYANPURI");
INSERT INTO graphs_vertices(name) VALUES ("NEHRU PLACE TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("SANT NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("MOOL CHAND KHARATI RAM HOSPITAL");
INSERT INTO graphs_vertices(name) VALUES ("PANT NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("SUNDER NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("PRAGATI MAIDAN");
INSERT INTO graphs_vertices(name) VALUES ("I.T.O(RING ROAD)");
INSERT INTO graphs_vertices(name) VALUES ("RAINY WELL");
INSERT INTO graphs_vertices(name) VALUES ("SHAKAR PUR");
INSERT INTO graphs_vertices(name) VALUES ("JAGAT PURI A-BLOCK");
INSERT INTO graphs_vertices(name) VALUES ("SWARN CINEMA");
INSERT INTO graphs_vertices(name) VALUES ("SEELAM PUR");
INSERT INTO graphs_vertices(name) VALUES ("BABARPUR");
INSERT INTO graphs_vertices(name) VALUES ("JYOTI COLONY");
INSERT INTO graphs_vertices(name) VALUES ("NAND NAGAR TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("NEHRU PLACE TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("SANT NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("L.S.R COLLEGE");
INSERT INTO graphs_vertices(name) VALUES ("ANDREWS GANJ");
INSERT INTO graphs_vertices(name) VALUES ("PT COLLEGE KOTLA");
INSERT INTO graphs_vertices(name) VALUES ("SUKHDEV MARKET KOTLA");
INSERT INTO graphs_vertices(name) VALUES ("JAWAHAR LAL NEHRU STADIUM");
INSERT INTO graphs_vertices(name) VALUES ("KHAN MARKET");
INSERT INTO graphs_vertices(name) VALUES ("BARODA HOUSE");
INSERT INTO graphs_vertices(name) VALUES ("PATIALA HOUSE");
INSERT INTO graphs_vertices(name) VALUES ("SUPREME COURT");
INSERT INTO graphs_vertices(name) VALUES ("ITO AGCR");
INSERT INTO graphs_vertices(name) VALUES ("RAINY WELL");
INSERT INTO graphs_vertices(name) VALUES ("LAXMI NAGAR");
INSERT INTO graphs_vertices(name) VALUES ("NIRMAN VIHAR");
INSERT INTO graphs_vertices(name) VALUES ("NEW RAJDHANI ENCLAVE");
INSERT INTO graphs_vertices(name) VALUES ("DDA FLATS KARKADOMA");
INSERT INTO graphs_vertices(name) VALUES ("YAMUNA SPORTS COMPLEX");
INSERT INTO graphs_vertices(name) VALUES ("RAMAPRASTH XING");
INSERT INTO graphs_vertices(name) VALUES ("SHAHDARA BORDER");
INSERT INTO graphs_vertices(name) VALUES ("DILSHAD GARDEN POCKET P");
INSERT INTO graphs_vertices(name) VALUES ("NEHRU PLACE TERMINAL");
INSERT INTO graphs_vertices(name) VALUES ("PARAS CINEMA");
INSERT INTO graphs_vertices(name) VALUES ("MODI MILL");
INSERT INTO graphs_vertices(name) VALUES ("GARHI VILLAGE");
INSERT INTO graphs_vertices(name) VALUES ("P.G.D.A.V COLLEGE");
INSERT INTO graphs_vertices(name) VALUES ("MAHARANI BAGH");
INSERT INTO graphs_vertices(name) VALUES ("GURUDWARA SRI BANGLA SAHIB");
INSERT INTO graphs_vertices(name) VALUES ("PWD OFFICE");
INSERT INTO graphs_vertices(name) VALUES ("MAYUR VIHAR PHASE-1");
INSERT INTO graphs_vertices(name) VALUES ("MAYUR KUNJ");
INSERT INTO graphs_vertices(name) VALUES ("SECTOR 15");
INSERT INTO graphs_vertices(name) VALUES ("RAJNI GANDHA CHOWL");
INSERT INTO graphs_vertices(name) VALUES ("BSNL SECTOR-19");
INSERT INTO graphs_vertices(name) VALUES ("NOIDA STADIUM");
INSERT INTO graphs_vertices(name) VALUES ("NOIDA SECTOR 12-22");
INSERT INTO graphs_vertices(name) VALUES ("ROYAL TOWERS");
INSERT INTO graphs_vertices(name) VALUES ("SABJI MANDI BUS STOP");
INSERT INTO graphs_vertices(name) VALUES ("RO APARTMENTS");
INSERT INTO graphs_vertices(name) VALUES ("FORTIS HOSPITAL");
INSERT INTO graphs_vertices(name) VALUES ("SECTOR-62");