# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vertex1', models.CharField(max_length=150)),
                ('Vertex2', models.CharField(max_length=150)),
                ('Weight', models.BigIntegerField()),
                ('Cost', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vertices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
