# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edges',
            name='Cost',
        ),
    ]
