# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_remove_edges_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=150)),
                ('Path', models.TextField(max_length=400000)),
            ],
        ),
    ]
