# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', 'migrationfile'),
        ('graphs', '0003_bus'),
    ]

    operations = [
    ]
